.TH EAGLE 1 EAGLE
.SH NAME
eagle \- A modern Lightweight whois client Written in C.
.SH OPTIONS
.B eagle [host] [OPTIONS]
.SH DESCRIPTION
.B sple
eagle-whois is a Lighter whois client.
.SH OPTIONS
.TP
.B \-h
the host/IP.
.TP
.B \-i
get host IP address(s).
.TP
.B \-f
send whois flag to the server.
.TP
.B \-F
send only whois flag to the server.
.TP
.B \-n
hide whois comments.
.TP
.B \-g
will try to get host/IP geolocation.
.TP
.B \-s
connect to a server.
.TP
.B \-c
highlight Email, Person etc..
.TP
.B \-v
show version information
.TP
.B \-h
print help.
.SH AUTHORS
Copyright (c) 2015 by Hypsurus <hypsurus@mail.ru>
.SH LICENSE
See the LICENSE file for the terms of redistribution.
.SH SEE ALSO
.BR whois (1)
.BR host (1)
.SH BUGS
Please report them to hypsurus@mail.ru.

